apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: cicd-taskrun-test
spec:
  taskRef:
    name: test
  resources:
    inputs:
      - name: repo
        resourceRef:
          name: cicd-pipelineresource-git
